"""empty message

Revision ID: 10a381849bd7
Revises: 27e58d4b4034
Create Date: 2015-08-12 12:36:22.690000

"""

# revision identifiers, used by Alembic.
revision = '10a381849bd7'
down_revision = '27e58d4b4034'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('first_log', sa.DateTime(), nullable=True))
    op.add_column('member', sa.Column('last_log', sa.DateTime(), nullable=True))
    op.add_column('member', sa.Column('logins', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'logins')
    op.drop_column('member', 'last_log')
    op.drop_column('member', 'first_log')
    ### end Alembic commands ###
