"""empty message

Revision ID: 11726294a000
Revises: None
Create Date: 2015-08-06 14:15:50.994000

"""

# revision identifiers, used by Alembic.
revision = '11726294a000'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('surnmame', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('pwdhash', sa.String(), nullable=False),
    sa.Column('adminr', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('surnmame')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    ### end Alembic commands ###
