"""empty message

Revision ID: 189b7e15d593
Revises: 21777359a094
Create Date: 2015-08-13 15:59:18.728000

"""

# revision identifiers, used by Alembic.
revision = '189b7e15d593'
down_revision = '21777359a094'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
