"""empty message

Revision ID: 21777359a094
Revises: 2a0b5c317f7d
Create Date: 2015-08-13 15:09:27.293000

"""

# revision identifiers, used by Alembic.
revision = '21777359a094'
down_revision = '2a0b5c317f7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'active')
    ### end Alembic commands ###
