"""empty message

Revision ID: 27e58d4b4034
Revises: 2d71ad4a8695
Create Date: 2015-08-06 16:52:46.049000

"""

# revision identifiers, used by Alembic.
revision = '27e58d4b4034'
down_revision = '2d71ad4a8695'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
