"""empty message

Revision ID: 2a0b5c317f7d
Revises: 10a381849bd7
Create Date: 2015-08-12 12:59:21.619000

"""

# revision identifiers, used by Alembic.
revision = '2a0b5c317f7d'
down_revision = '10a381849bd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
