"""empty message

Revision ID: 2d71ad4a8695
Revises: 11726294a000
Create Date: 2015-08-06 15:12:52.377000

"""

# revision identifiers, used by Alembic.
revision = '2d71ad4a8695'
down_revision = '11726294a000'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('surname', sa.String(length=30), nullable=False))
    op.drop_column('member', u'surnmame')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column(u'surnmame', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('member', 'surname')
    ### end Alembic commands ###
