"""empty message

Revision ID: 2d9012a5d43e
Revises: 4345f73db880
Create Date: 2015-08-26 16:08:30.211000

"""

# revision identifiers, used by Alembic.
revision = '2d9012a5d43e'
down_revision = '4345f73db880'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
