"""empty message

Revision ID: 3667808d80df
Revises: 47f1a40a18e
Create Date: 2015-08-27 13:19:00.954000

"""

# revision identifiers, used by Alembic.
revision = '3667808d80df'
down_revision = '47f1a40a18e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
