"""empty message

Revision ID: 4345f73db880
Revises: 4597a648d05a
Create Date: 2015-08-26 14:12:58.662000

"""

# revision identifiers, used by Alembic.
revision = '4345f73db880'
down_revision = '4597a648d05a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
