"""empty message

Revision ID: 43696a8e5903
Revises: 5198a74112fc
Create Date: 2015-12-08 18:18:29.895000

"""

# revision identifiers, used by Alembic.
revision = '43696a8e5903'
down_revision = '5198a74112fc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('motioncapture', sa.Column('last_log', sa.DateTime(), nullable=True))
    op.add_column('motioncapture', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'motioncapture', 'member', ['member_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'motioncapture', type_='foreignkey')
    op.drop_column('motioncapture', 'member_id')
    op.drop_column('motioncapture', 'last_log')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###
