"""empty message

Revision ID: 4597a648d05a
Revises: 51b0376f3f1f
Create Date: 2015-08-26 09:12:11.158000

"""

# revision identifiers, used by Alembic.
revision = '4597a648d05a'
down_revision = '51b0376f3f1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
