"""empty message

Revision ID: 47f1a40a18e
Revises: 2d9012a5d43e
Create Date: 2015-08-27 10:06:41.228000

"""

# revision identifiers, used by Alembic.
revision = '47f1a40a18e'
down_revision = '2d9012a5d43e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'member_surname_key', 'member', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'member_surname_key', 'member', ['surname'])
    ### end Alembic commands ###
