"""empty message

Revision ID: 4c387161246d
Revises: 3667808d80df
Create Date: 2015-08-27 13:27:02.148000

"""

# revision identifiers, used by Alembic.
revision = '4c387161246d'
down_revision = '3667808d80df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
