"""empty message

Revision ID: 5198a74112fc
Revises: 2c5fc0f9ad45
Create Date: 2015-11-20 15:45:21.920000

"""

# revision identifiers, used by Alembic.
revision = '5198a74112fc'
down_revision = '2c5fc0f9ad45'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motioncapture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acx', sa.String(), nullable=True),
    sa.Column('acy', sa.String(), nullable=True),
    sa.Column('theta', sa.String(), nullable=True),
    sa.Column('beta', sa.String(), nullable=True),
    sa.Column('gamma', sa.String(), nullable=True),
    sa.Column('radius', sa.String(), nullable=True),
    sa.Column('angle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('apscheduler_jobs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_table('motioncapture')
    ### end Alembic commands ###
