"""empty message

Revision ID: 51b0376f3f1f
Revises: 4e0194f32690
Create Date: 2015-08-25 18:03:50.819000

"""

# revision identifiers, used by Alembic.
revision = '51b0376f3f1f'
down_revision = '4e0194f32690'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'confirmed')
    ### end Alembic commands ###
